name: Generate snake animation

on:
  schedule:
    - cron: "0 */12 * * *"

  workflow_dispatch:

  push:
    branches:
    - master

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout código
        uses: actions/checkout@v2

      - name: Generar snake.svg
        uses: Platane/snk@v2
        with:
          snake_color: "#68B7E3"
          background_color: "#282C34"
          output_file: dist/snake.svg
          user_id: Paola2005

      - name: Agregar snake.svg a la rama de salida
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add dist/snake.svg
          git commit -m "Actualizar snake.svg"
          git push

      - name: Publicar snake.svg en GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: gh-pages
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
